packages:
  - model
  - server
  - ui

allowBuilds:
  bufferutil: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  protobufjs: true
  unrs-resolver: true

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - lmdb
  - msgpackr-extract
  - protobufjs
  - unrs-resolver
