packages:
  - model
  - server
  - ui

allowBuilds:
  bufferutil: true
  esbuild: true
  protobufjs: true
  unrs-resolver: true

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - protobufjs
  - unrs-resolver
